title: Knowledge Base Article

columns:
  main:
    sections:
      fields:
        type: fields
        fields:
          blocks:
            type: blocks
            size: huge
            fieldsets:
              - heading
              - text
              - card
              - link-card
              - become-member
              - image
          access:
            label: Page Access
            type: select
            default: all
            options:
              all: All
              member: Members
              contributor: Contributors
              admin: Admins
